name: Check
on:
  - push
  - pull_request

jobs:
  check:
    name: npm run check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Volta
      uses: volta-cli/action@v4
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Use npm run check
      run: npm run check
