name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: npm install-ci-test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Volta
        uses: volta-cli/action@v4
      - name: Check out code
        uses: actions/checkout@v4
      - run: npm install-ci-test
